SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE WELCOME(MY_NAME IN VARCHAR2)
IS
BEGIN
dbms_output.put_line('Welcome ' || MY_NAME);
END;
/

exec WELCOME('rahil');

CREATE OR REPLACE FUNCTION DO_LOGIN(EMAIL IN VARCHAR2,PASSWD IN VARCHAR2) RETURN INT
IS
    MY_COUNT INT := 0;
BEGIN
    SELECT COUNT(ACCESS_ID) INTO MY_COUNT FROM ACCESS_USER WHERE EMAILID = EMAIL AND U_PASSWD = PASSWD;
    RETURN MY_COUNT;
END;
/


declare
   result number;
begin
   -- Call the function
   result := DO_LOGIN('PATHANRAHIL143@GMAIL.COM','Um9uYWxkbzE0Mw==');
   dbms_output.put_line('Result  ' || result);
end;
/

CREATE OR REPLACE PROCEDURE CREATE_USER
    (F_NAME IN ACCESS_USER.FIRST_NAME%TYPE,
    M_NAME IN ACCESS_USER.MIDDLE_NAME%TYPE,
    S_NAME IN ACCESS_USER.SUR_NAME%TYPE,
    U_EMAIL IN ACCESS_USER.EMAILID%TYPE,
    P_NUMBER IN ACCESS_USER.PHONE_NUMBER%TYPE,
    PASWD IN ACCESS_USER.U_PASSWD%TYPE)
IS
    USERID INT := SEQ_ACCESS_USER.NEXTVAL;
    STATUS CHAR :='Y';
BEGIN
    INSERT INTO ACCESS_USER(ACCESS_ID,FIRST_NAME,MIDDLE_NAME,SUR_NAME,EMAILID,PHONE_NUMBER,ENABLED,U_PASSWD) 
    VALUES(USER_ID,F_NAME,M_NAME,S_NAME,U_EMAIL,P_NUMBER,STATUS,PASWD);
END;
/




